// packages/react/playground/vite-app/src/components/ResizeBounding.tsx
import ResizeBoundingComponent, {
  globalClassNames,
  PREFIX,
  type Props,
  type IStyles,
} from "react-resize-bounding";

import { colors } from "./colors";

const styles: Partial<IStyles> = {
  splitter: [
    globalClassNames(PREFIX).splitter,
    {
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
  knob: [
    globalClassNames(PREFIX).knob,
    {
      height: "10px",
      borderRadius: "5px",
      background: `${colors.resizerKnobNormal}`,
      border: `2px solid ${colors.backgroundSecondary}`,
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
};

const ResizeBounding = (props: Props) => {
  return (
    <ResizeBoundingComponent
      {...props}
      options={{
        width: 6,
        activeAreaWidth: 16,
        knob: {
          show: true,
        },
      }}
      styles={styles}
    >
      {props.children}
    </ResizeBoundingComponent>
  );
};

export default ResizeBounding;

// packages/vue/playground/vite-app/src/components/ResizeBounding.vue
<template>
  <ResizeBounding
    :options="{
      width: 6,
      activeAreaWidth: 16,
      knob: {
        show: true,
      },
    }"
    :styles
  >
    <slot></slot>
  </ResizeBounding>
</template>

<script setup lang="ts">
import ResizeBounding, {
  globalClassNames,
  PREFIX,
  type IStyles,
} from "vue3-resize-bounding";

import { colors } from "@/components/colors";

const styles: Partial<IStyles> = {
  splitter: [
    globalClassNames(PREFIX).splitter,
    {
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
  knob: [
    globalClassNames(PREFIX).knob,
    {
      height: "10px",
      borderRadius: "5px",
      background: `${colors.resizerKnobNormal}`,
      border: `2px solid ${colors.backgroundSecondary}`,
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
};
</script>
