// packages/playground/vite-app/src/components/InteractiveGrid.vue
<template>
  <main class="boundarize-app">
    <div class="boundarize-app--container">
      <div class="boundarize-app__layout">
        <ResizeBounding
          :height="layout.a.height"
          :min-height="layout.a.minHeight"
          :max-height="layout.a.maxHeight"
          :directions="'b'"
          :style="{ borderBottom: '1px solid gray' }"
          @update:height="
            (height) => {
              layout.a.height = height;
            }
          "
        >
          <UIInnerBlock :title="layout.a.title">
            <UISizeField
              :height="layout.a.height"
              @update:height="
                (height) => {
                  layout.a.height = height;
                }
              "
            />
          </UIInnerBlock>
        </ResizeBounding>
        <ResizeBounding
          :directions="''"
          :style="[{ display: 'flex', height: '100%' }]"
        >
          <ResizeBounding
            :width="layout.b.width"
            :min-width="layout.b.minWidth"
            :max-width="layout.b.maxWidth"
            :directions="'r'"
            :style="[{ display: 'flex', borderRight: '1px solid gray' }]"
            @update:width="
              (width) => {
                layout.b.width = width;
              }
            "
          >
            <UIInnerBlock :title="layout.b.title">
              <UISizeField
                :width="layout.b.width"
                @update:width="
                  (width) => {
                    layout.b.width = width;
                  }
                "
              />
            </UIInnerBlock>
          </ResizeBounding>
          <UIInnerBlock :title="layout.c.title">
            <UISizeField />
          </UIInnerBlock>
          <ResizeBounding
            :width="layout.d.width"
            :min-width="layout.d.minWidth"
            :max-width="layout.d.maxWidth"
            :directions="'l'"
            :style="{ borderLeft: '1px solid gray' }"
            @update:width="
              (width) => {
                layout.d.width = width;
              }
            "
          >
            <UIInnerBlock :title="layout.d.title">
              <UISizeField
                :width="layout.d.width"
                @update:width="
                  (width) => {
                    layout.d.width = width;
                  }
                "
              />
            </UIInnerBlock>
          </ResizeBounding>
        </ResizeBounding>
        <ResizeBounding
          :height="layout.e.height"
          :min-height="layout.e.minHeight"
          :max-height="layout.e.maxHeight"
          :directions="'t'"
          :style="[
            { display: 'flex', width: '100%', borderTop: '1px solid gray' },
          ]"
          @update:height="
            (height) => {
              layout.e.height = height;
            }
          "
        >
          <ResizeBounding
            :width="layout.e.width"
            :min-width="layout.e.minWidth"
            :max-width="layout.e.maxWidth"
            :directions="'r'"
            :style="{
              borderRight: '1px solid gray',
            }"
            @update:width="
              (width) => {
                layout.e.width = width;
              }
            "
          >
            <UIInnerBlock :title="layout.e.title">
              <UISizeField
                :width="layout.e.width"
                :height="layout.e.height"
                @update:width="
                  (width) => {
                    layout.e.width = width;
                  }
                "
                @update:height="
                  (height) => {
                    layout.e.height = height;
                  }
                "
              />
            </UIInnerBlock>
          </ResizeBounding>
          <ResizeBounding
            :directions="''"
            :style="[{ display: 'flex', width: '100%' }]"
          >
            <UIInnerBlock :title="layout.f.title">
              <UISizeField
                :height="layout.e.height"
                @update:height="
                  (height) => {
                    layout.e.height = height;
                  }
                "
              />
            </UIInnerBlock>
          </ResizeBounding>
        </ResizeBounding>
      </div>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref, type Ref } from "vue";

import { UIInnerBlock, UISizeField } from "ui";
import "ui/style.css";

import ResizeBounding from "vue3-resize-bounding";

interface ContainerSize {
  width: number;
  minWidth: number;
  maxWidth: number;
  height: number;
  minHeight: number;
  maxHeight: number;
}

const layout: Ref<
  Record<
    "a" | "c" | "b" | "e" | "d" | "f",
    Partial<ContainerSize & { title: string }>
  >
> = ref({
  a: {
    height: 200,
    minHeight: 200,
    maxHeight: 320,
    title: "A",
  },
  b: {
    width: 320,
    minWidth: 240,
    maxWidth: 640,
    title: "B",
  },
  c: {
    width: 360,
    title: "C",
  },
  d: {
    width: 320,
    minWidth: 240,
    maxWidth: 640,
    title: "D",
  },
  e: {
    height: 320,
    minHeight: 240,
    maxHeight: 400,
    width: 640,
    minWidth: 240,
    maxWidth: 640,
    title: "E",
  },
  f: {
    title: "F",
  },
});
</script>

<style lang="scss">
$__border-color: gray;
$__background--primary: #e8ebec;

%container--normal {
  background: $__background--primary;
}

.boundarize-app {
  display: flex;
  @include box(100%);

  * {
    user-select: none;
  }

  &--container {
    @include box(100%);
    padding: 20px;
    box-sizing: border-box;
  }

  &__layout {
    display: flex;
    flex-direction: column;
    @include box(100%);
    @extend %container--normal;
    border: 1px solid $__border-color;
    border-radius: 24px;
    overflow: hidden;
  }
}
</style>

// packages/react/playground/vite-app/src/components/InteractiveGrid.tsx
import { useReducer } from "react";

import ResizeBounding from "react-resize-bounding";
import deepmerge from "deepmerge";

import "./InteractiveGrid.scss";

import UIInnerBlock from "@/components/helpers/UIInnerBlock";
import UISizeField from "@/components/helpers/UISizeField";

import {
  type Actions,
  type ContainerSizeKeys,
  initState,
  LayoutKeys,
  ActionTypes,
} from "./layout.store";

const layoutReducer = (
  state: typeof initState,
  action: Actions,
): typeof initState => {
  const { type, payload } = action;
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [sectionKey, propKey] = type.toLowerCase().split("_");

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  for (const [_, v] of Object.entries(LayoutKeys)) {
    if (sectionKey === v) {
      return deepmerge(
        state,
        (state[sectionKey][propKey as ContainerSizeKeys] = payload),
      );
    }
  }

  throw new Error("Invalid action name!");
};

const InteractiveGrid = () => {
  const [layout, dispatch] = useReducer(layoutReducer, initState);

  return (
    <main className="boundarize-app">
      <div className="boundarize-app--container">
        <div className="boundarize-app__layout">
          <ResizeBounding
            height={layout.a.height}
            minHeight={layout.a.minHeight}
            maxHeight={layout.a.maxHeight}
            directions="b"
            style={{ borderBottom: "1px solid gray" }}
            updateHeight={(height) => {
              dispatch({ type: ActionTypes.SET_A_HEIGHT, payload: height });
            }}
          >
            <UIInnerBlock title={layout.a.title}>
              <UISizeField
                height={layout.a.height}
                updateHeight={(height) => {
                  layout.a.height = height;
                }}
              />
            </UIInnerBlock>
          </ResizeBounding>
          <ResizeBounding
            directions="''"
            style={{ display: "flex", height: "100%" }}
          >
            <ResizeBounding
              width={layout.b.width}
              min-width={layout.b.minWidth}
              max-width={layout.b.maxWidth}
              directions="'r'"
              style={{ display: "flex", borderRight: "1px solid gray" }}
              updateWidth={(width) => {
                dispatch({ type: ActionTypes.SET_B_WIDTH, payload: width });
              }}
            >
              <UIInnerBlock title={layout.b.title}>
                <UISizeField
                  width={layout.b.width}
                  updateWidth={(width) => {
                    layout.b.width = width;
                  }}
                />
              </UIInnerBlock>
            </ResizeBounding>
            <UIInnerBlock title={layout.c.title}>
              <UISizeField />
            </UIInnerBlock>
            <ResizeBounding
              width={layout.d.width}
              min-width={layout.d.minWidth}
              max-width={layout.d.maxWidth}
              directions="'l'"
              style={{ borderLeft: "1px solid gray" }}
              updateWidth={(width) => {
                dispatch({ type: ActionTypes.SET_D_WIDTH, payload: width });
              }}
            >
              <UIInnerBlock title={layout.d.title}>
                <UISizeField
                  width={layout.d.width}
                  updateWidth={(width) => {
                    layout.d.width = width;
                  }}
                />
              </UIInnerBlock>
            </ResizeBounding>
          </ResizeBounding>
          <ResizeBounding
            height={layout.e.height}
            min-height={layout.e.minHeight}
            max-height={layout.e.maxHeight}
            directions="'t'"
            style={{
              display: "flex",
              width: "100%",
              borderTop: "1px solid gray",
            }}
            updateHeight={(height) => {
              dispatch({ type: ActionTypes.SET_E_HEIGHT, payload: height });
            }}
          >
            <ResizeBounding
              width={layout.e.width}
              min-width={layout.e.minWidth}
              max-width={layout.e.maxWidth}
              directions="'r'"
              style={{
                borderRight: "1px solid gray",
              }}
              updateWidth={(width) => {
                dispatch({ type: ActionTypes.SET_E_WIDTH, payload: width });
              }}
            >
              <UIInnerBlock title={layout.e.title}>
                <UISizeField
                  width={layout.e.width}
                  height={layout.e.height}
                  updateWidth={(width) => {
                    layout.e.width = width;
                  }}
                  updateHeight={(height) => {
                    layout.e.height = height;
                  }}
                />
              </UIInnerBlock>
            </ResizeBounding>
            <ResizeBounding
              directions="''"
              style={{ display: "flex", width: "100%" }}
            >
              <UIInnerBlock title={layout.f.title}>
                <UISizeField
                  height={layout.e.height}
                  updateHeight={(height) => {
                    dispatch({
                      type: ActionTypes.SET_E_HEIGHT,
                      payload: height,
                    });
                  }}
                />
              </UIInnerBlock>
            </ResizeBounding>
          </ResizeBounding>
        </div>
      </div>
    </main>
  );
};

export default InteractiveGrid;
