// demo/components/atoms/container/ResizeBounding.vue
<template>
  <Resizer
    :options="{
      prefix: PREFIX,
      width: 4,
      activeAreaWidth: undefined,
      position: 'central',
      knob: {
        show: true,
      },
      touchActions: true,
    }"
    :styles="{
      knob: [
        globalClassNames(PREFIX).knob,
        {
          width: '64px',
          height: '6px',
          borderRadius: '4px',
          transition: 'background 75ms ease-out',
        },
      ],
    }"
  >
    <slot></slot>
  </Resizer>
</template>

<script setup lang="ts">
import Resizer, { globalClassNames } from "vue3-resize-bounding";

const PREFIX = "ui-resizer__";
</script>

<style lang="scss">
$prefix: "ui-resizer__";

.#{$prefix} {
  &pane {
    // normal state:
    .#{$prefix}splitter {
      @include themify($app-themes) {
        background: transparentize(themed("colors", "accent"), 1);
      }
    }

    .#{$prefix}knob {
      @include themify($app-themes) {
        background: themed("resizer", "knob");
        border: 1px solid themed("background", "secondary");
      }
    }

    // selected pane:
    &.active {
      .#{$prefix}splitter {
        @include themify($app-themes) {
          background: transparentize(themed("colors", "accent"), 0);
        }
      }
    }
  }

  &splitter {
    @include transition(background, 125ms, ease-out);
  }
}
</style>

// packages/react/playground/vite-app/src/components/ResizeBounding.tsx
import ResizeBoundingComponent, {
  globalClassNames,
  PREFIX,
  type Props,
} from "react-resize-bounding";

import { colors } from "./colors";

const styles = {
  splitter: [
    globalClassNames(PREFIX).splitter,
    {
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
  knob: [
    globalClassNames(PREFIX).knob,
    {
      height: "10px",
      borderRadius: "5px",
      background: `${colors.resizerKnobNormal}`,
      border: `2px solid ${colors.backgroundSecondary}`,
      [`.${globalClassNames(PREFIX).pane}.active &`]: {
        background: `${colors.accent}`,
      },
    },
  ],
};

const ResizeBounding = (props: Props) => {
  return (
    <ResizeBoundingComponent
      {...props}
      options={{
        width: 6,
        activeAreaWidth: 16,
        knob: {
          show: true,
        },
      }}
      styles={styles}
    >
      {props.children}
    </ResizeBoundingComponent>
  );
};

export default ResizeBounding;
