// demo/components/atoms/UISizeField.vue
<template>
  <div class="ui-size-field">
    <UIInput
      label="W:"
      :value="width"
      :disabled="width === undefined"
      @update:value="
        (width) => {
          $emit('update:width', width);
        }
      "
    />
    <UIInput
      label="H:"
      :value="height"
      :disabled="height === undefined"
      @update:value="
        (height) => {
          $emit('update:height', height);
        }
      "
    />
  </div>
</template>

<script setup lang="ts">
import UIInput from "./UIInput.vue";

interface Props {
  width?: number;
  height?: number;
  label?: string;
}

defineProps<Props>();

defineEmits<{
  (e: "update:width", value: number): void;
  (e: "update:height", value: number): void;
}>();
</script>

<style lang="scss">
$__background--primary: #e8ebec;

.ui {
  &-size-field {
    display: grid;
    grid-template-columns: 1fr 1fr;
    height: 36px;
    background-color: $__background--primary;
    border-radius: 24px;
    color: black;

    .ui-input {
      &:not(:last-child) {
        border-right: 1px solid rgba(0, 0, 0, 0.2);
      }
    }

    input {
      width: 44px;
    }
  }
}
</style>

// packages/react/playground/vite-app/src/components/helpers/UISizeField.tsx
import { PropsWithChildren } from "react";

import UIInput from "./UIInput";
import "./UISizeField.scss";

interface Props extends PropsWithChildren {
  width?: number;
  height?: number;
  label?: string;
  updateWidth?: (width: number) => void;
  updateHeight?: (height: number) => void;
}

const UISizeField = ({ width, height, updateWidth, updateHeight }: Props) => {
  return (
    <div className="ui-size-field">
      <UIInput
        label={"W:"}
        value={width}
        disabled={width === undefined}
        updateValue={(width) => {
          typeof updateWidth === "function" && updateWidth(width);
        }}
      />
      <UIInput
        label={"H:"}
        value={height}
        disabled={height === undefined}
        updateValue={(height) => {
          typeof updateHeight === "function" && updateHeight(height);
        }}
      />
    </div>
  );
};

export default UISizeField;
