// packages/vue/playground/vite-app/src/components/helpers/UISizeField.vue
<template>
  <div
    class="ui-size-field"
    :style="{
      backgroundColor: colors.backgroundSecondary,
      color: colors.foregroundSecondary,
    }"
  >
    <HInput
      label="W:"
      :value="width"
      :disabled="width === undefined"
      @update:value="
        (width) => {
          $emit('update:width', width);
        }
      "
    />
    <HInput
      label="H:"
      :value="height"
      :disabled="height === undefined"
      @update:value="
        (height) => {
          $emit('update:height', height);
        }
      "
    />
  </div>
</template>

<script setup lang="ts">
import HInput from "./UIInput.vue";

import { colors } from "@/components/colors";

interface Props {
  width?: number;
  height?: number;
  label?: string;
}

defineProps<Props>();

defineEmits<{
  (e: "update:width", width: number): void;
  (e: "update:height", height: number): void;
}>();
</script>

<style lang="scss">
.ui {
  &-size-field {
    display: grid;
    grid-template-columns: 1fr 1fr;
    height: 36px;
    border-radius: 24px;

    .ui-input {
      &:not(:last-child) {
        border-right: 1px solid rgba(255, 255, 255, 0.2);
      }
    }

    input {
      width: 44px;
    }
  }
}
</style>

// packages/react/playground/vite-app/src/components/helpers/UISizeField.tsx
import { PropsWithChildren } from "react";

import UIInput from "./UIInput";
import "./UISizeField.scss";

import { colors } from "@/components/colors";
interface Props extends PropsWithChildren {
  width?: number;
  height?: number;
  label?: string;
  updateWidth?: (width: number) => void;
  updateHeight?: (height: number) => void;
}

const UISizeField = ({ width, height, updateWidth, updateHeight }: Props) => {
  return (
    <div
      className="ui-size-field"
      style={{
        backgroundColor: colors.backgroundSecondary,
        color: colors.foregroundSecondary,
      }}
    >
      <UIInput
        label={"W:"}
        value={width}
        disabled={width === undefined}
        updateValue={(width) => {
          updateWidth?.(width);
        }}
      />
      <UIInput
        label={"H:"}
        value={height}
        disabled={height === undefined}
        updateValue={(height) => {
          updateHeight?.(height);
        }}
      />
    </div>
  );
};

export default UISizeField;
